version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: weather-app-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./server/weather.db:/app/weather.db
      - ./server/src:/app/src:ro
    restart: unless-stopped
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/cities"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: weather-app-ui
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  weather-network:
    driver: bridge

volumes:
  weather_db:
    driver: local
