version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: weather-app-server-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - weather-network-dev
    command: ["bun", "run", "--watch", "src/index.ts"]

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    container_name: weather-app-ui-dev
    ports:
      - "4000:4000"
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - weather-network-dev
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "4000"]

networks:
  weather-network-dev:
    driver: bridge
